services:
  app:
    build: .
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/home/node/app

  db:
    image: postgis/postgis:15-3.4-alpine
    environment:
      POSTGRES_DB: eduardomuchak
      POSTGRES_USER: eduardomuchak
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql
